### ISSUE TITLE
Problems with version updates to apollo-server and with typegraphql

### ISSUE THREAD

**Issue by PSPanesar** [benawad/type-graphql-series#13]
Hi Ben,

I've just tried to install the server with updated versions to latest for typegraphql and apollo and ran into some errors.

I've fixed most of them but i'm stuck with this one:

UnhandledPromiseRejectionWarning: Error: Schema must contain uniquely named types but contains multiple types named "PasswordInput".

I wonder if you had any advice on fixing this?

**Comment by benawad** [comment]
```
@InputType({ isAbstract: true })
```
