### ISSUE TITLE
Can't import formatArgumentValidationError from type-graphql

### ISSUE THREAD

**Issue by sathish-spidie** [benawad/type-graphql-series#17]
Hi,

I just wanted to tell you about this problem, I can't import formatArgumentValidationError from type-graphql,

My tslint : Module '"../../TypeGraphql/node_modules/type-graphql/dist"' has no exported member 'formatArgumentValidationError'.

And i'm using tsconfig as in this repo.

Cheers

**Comment by sathish-spidie** [comment]
S

**Comment by sathish-spidie** [comment]
Sorry it's a silly mistake, i have to import it as default.

**Comment by Elbarae1921** [comment]
I'm having the exact same issue, how did you solve it ? @sathish-spidie

**Comment by slinden2** [comment]
> I'm having the exact same issue, how did you solve it ? @sathish-spidie

Check [0.17.0 release notes](https://github.com/MichalLytek/type-graphql/releases/tag/v0.17.0). It was removed due to type compatibility issues with Apollo.

**Comment by sifat0666** [comment]
have they replaced it with something?

**Comment by TomixUG** [comment]
> have they replaced it with something?

It's no longer needed to use the `formatError`. It does everything by default now.
