### ISSUE TITLE
Register resolver test returns null

### ISSUE THREAD

**Issue by ishank-s** [benawad/type-graphql-series#22]
Register functionality is doing fine but the test seems to return null on data.
Register › create user

    expect(received).toMatchObject(expected)

    - Expected
    + Received

      Object {
    -   "data": Object {
    -     "register": Object {
    -       "email": "Kurtis_Hamill53@hotmail.com",
    -       "firstName": "Reginald",
    -       "lastName": "Windler",
    -     },
    -   },
    +   "data": null,
      }

      44 |     });
      45 | 

 at src/modules/user/register/Register.test.ts:46:22
      at fulfilled (src/modules/user/register/Register.test.ts:5:58)

**Comment by benawad** [comment]
Is this after cloning the project?

**Comment by ishank-s** [comment]
First followed along, then just copied the source dir since config would be different

**Comment by benawad** [comment]
Try adding some console.logs to see why the resolver returns null

**Comment by ishank-s** [comment]
Hi thanks for your prompt response, i'll update this on the weekend.
PS: Thanks for your tutorial sir. Maybe start a patreon/Subscribe star

**Comment by benawad** [comment]
@prophet1996  https://www.patreon.com/benawad

**Comment by ishank-s** [comment]
Started running all the same. Prob env issue
